# ----------------------------------------------------------
# This is a makefile.  A makefile contains rules that tell
# how to build a program, often from separate source files
#
# This sample makefile shows how to build dumputmp from
# the two source files dumputmp.c and utmplib.c
#
# You must modify this file so it contains rules to make
# your solution to the project
# (note: the indented lines MUST start with a single tab
#

CC = gcc -Wall

pong: pong.c
	$(CC) pong.c paddle.c alarm.c -lcurses -o pong

clean:
	rm -f pong *.o



